#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d     
bspc monitor HDMI-0 -d   

bspc config border_width         2
bspc config window_gap          17
bspc config top_padding		30


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#cc9f9f"
bspc config active_border_color "#cc9f9f"
bspc config focused_border_color "#FCC7C7"

xsetroot -cursor_name left_ptr

steamlib=/games/SteamLibrary    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^10 state=fullscreen
done

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a fteam desktop='^1'
bspc rule -a discord desktop='^5'
bspc rule -a steam desktop='^6'
bspc rule -a Thunar desktop='^4'
bspc rule -a Lutris desktop='^3'
bspc rule -a Spotify desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.screenlayout/monitor.sh &
sxhkd &
picom --config  ~/.config/picomConf.conf --experimental-backends &
feh --bg-fill /home/bruna/Wallpapers/retro.png &
~/.config/polybar/launch.sh &
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
discord &
steam &

